[package]
name = "traceguard"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.5", features = ["headers", "multipart"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid", "json"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.3", features = ["trace"] }
jsonwebtoken = "8.1"
bcrypt = "0.10"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tonic = "0.8"
prost = "0.11"
openidconnect = "2.4"
reqwest = { version = "0.11", features = ["json"] }
async-trait = "0.1"
dotenv = "0.15"
log = "0.4"
env_logger = "0.9"

[workspace]
members = ["web_ui"]

[dev-dependencies]
mockall = "0.11"