name: Continuous Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run tests
      run: cargo test --verbose
    - name: Run encryption tests
      run: cargo test --test encryption_tests -- --test-threads=1

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo build --release
        cd web_ui && npm run build
        cd ../cli && go build -o traceguard

    - name: Set up Porter
      uses: getporter/gh-action@v0.1.3
      with:
        porter_version: v0.38.4

    - name: Build Porter bundle
      run: porter build

    - name: Publish Porter bundle
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        porter publish

    - name: Deploy
      run: |
        porter install --credential-set kubernetes --param vault_version=1.8.2
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
